### ISSUE TITLE
readme missing

### ISSUE THREAD

**Issue by si458** [Devolutions/WaykClient-ps#3]
readme is missing?
whats the new powershell functions?
how to deal with migrate from `wayknow-ps` to `waykclient-ps`

**Comment by awakecoding** [comment]
All docs have been moved to https://docs.devolutions.net/wayk/
Those docs are generated from this repository: https://github.com/Devolutions/devolutions-docs

As you can see, 2020.3 was a big release, and a lot has been moved around. Expect a few things like this.
